openapi: '3.0.2'
info:
  title: Chromist API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  "/home/getThreads/{pageNumber}":
    get:
      summary: Get page of threads
      operationId: getThreads
      parameters:
        - name: page number
          in: query
          description: The page number of which the threads need to be returned.
          required: false
          type: number
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Pet"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
security:
  - api_key: []
  - petstore_auth:
      - "write:pets"
      - "read:pets"

definitions:
  Thread:
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: "#/definitions/Category"
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      status:
        type: string
        description: pet status in the store
        enum:
          - available
          - pending
          - sold
    xml:
      name: Pet
